### ISSUE TITLE
Minimum Value on a number field set to 0

### ISSUE THREAD

**Issue by janmeeus** [barrelstrength/craft-sprout-forms#414]
### The problem (description, use case, screenshots...)
When using a number field, I can set the Min Value to "1", but when setting it to "0", it gets removed when Saving the form.

### The solution (that feature you'd like to see)
I would like to have a Min Value of 0, to prevent users going lower then 0 (like -1,-2,-3,…) by using the little arrow buttons on the number field.

### Alternatives you've considered
/

**Comment by BenParizek** [comment]
Thanks for reporting @janmeeus. I can recreate this and will update this thread once we have a fix out.

**Comment by BenParizek** [comment]
@janmeeus We've just released Sprout Forms v3.8.2 which should resolve this and let you set a min or max value to 0 now.

**Comment by janmeeus** [comment]
@BenParizek Thanks for the update. This works in the admin; I can set an Min Value to '0' and it gets saved.

However, when I test it in the front-end, the input field doesn't get `min="0"`
When setting the Min Value to 1, the number field does get `min="1"`

**Comment by BenParizek** [comment]
@janmeeus I am seeing zero output as a min value in my tests so perhaps we need to identify a difference in our setups to get to the bottom of this.

1. Have you copied the new Date field template from the latest release to your custom folder?
https://github.com/barrelstrength/craft-sprout-forms/blob/v3/src/templates/_components/formtemplates/basic/fields/date/input.twig

2. If so, You may want to dump `{{ dump(field.minimumDate) }}` to see what value the template thinks exist for that setting.

3. If not, do you have any other settings in place? I don't know what would be interfering with this but it may be good to see a screenshot of all the field settings just to make sure I'm trying to test the same thing.

**Comment by janmeeus** [comment]
> @janmeeus I am seeing zero output as a min value in my tests so perhaps we need to identify a difference in our setups to get to the bottom of this.
> 
> 1. Have you copied the new Date field template from the latest release to your custom folder?
>    https://github.com/barrelstrength/craft-sprout-forms/blob/v3/src/templates/_components/formtemplates/basic/fields/date/input.twig
> 2. If so, You may want to dump `{{ dump(field.minimumDate) }}` to see what value the template thinks exist for that setting.
> 3. If not, do you have any other settings in place? I don't know what would be interfering with this but it may be good to see a screenshot of all the field settings just to make sure I'm trying to test the same thing.

@BenParizek 
I have copied the new Date field template but this doesn't solve the issue. Are you testing with a Number field or a a Date field?

Here are screenshots:

Backend: Number field with Min value set to 0
![backend](https://user-images.githubusercontent.com/214060/74514064-2f4d0500-4f0c-11ea-9e28-9a3d14afe621.jpg)

Front-end Console: no min value on the input:
<img width="791" alt="Schermafbeelding 2020-02-14 om 08 42 44" src="https://user-images.githubusercontent.com/214060/74514086-32e08c00-4f0c-11ea-848b-446883526370.png">

I'm also using the latest Number field template.

**Comment by BenParizek** [comment]
@janmeeus My mistake. We had just released the date field and I probably just had it on my mind and mistakenly referenced it. I am testing with the Number field.

If you modify the Number field template and dump `{{ dump(field.minimumDate) }}`, what value does the template output?

**Comment by janmeeus** [comment]
@BenParizek you can see when I dump `field.min` it differs from when I dump `min`

<img width="181" alt="Schermafbeelding 2020-02-17 om 09 08 25" src="https://user-images.githubusercontent.com/214060/74634943-420e4680-5165-11ea-8fd3-d2e808ccaace.png">

So `{%- if field.min is not null %} min="{{ field.min }}"{% endif %}` works; the `min` variable doesn't.

**Comment by janmeeus** [comment]
@BenParizek Do you have time to look at this issue?

**Comment by BenParizek** [comment]
@janmeeus I'm seeing this behave as expected. Can you post the specific template you are using? The template you referenced – the [Basic Templates Number input](https://github.com/barrelstrength/craft-sprout-forms/blob/v3.8.4/src/templates/_components/formtemplates/basic/fields/number/input.twig) looks like this:

``` twig
{%- set id = renderingOptions.id ?? name %}
{%- set class = renderingOptions.class ?? name %}
{%- set required = field.required ? true : false %}
{%- set hasInstructions = field.instructions ? true : false %}
{%- set value = value ? value : null %}

{%- set min = field.min ? field.min : null %}
{%- set max = field.max ? field.max : null %}
{%- set decimals = field.decimals > 0 ? field.decimals : null %}

{%- set dataAttributes = null %}
{%- set data = renderingOptions.data ?? null %}
{%- for key, dataValue in data %}
    {%- set dataAttributes = dataAttributes ~ ' data-'~key~'="'~dataValue~'"' %}
{% endfor -%}

{%- set step = null %}
{%- if decimals -%}
    {%- for i in 1..decimals %}
        {%- set step = (loop.last ? step ~ 1 : step ~ 0) %}
    {%- endfor -%}
{%- endif -%}

<input type="number"
    {%- if name %} name="{{ name }}"{% endif %}
    {%- if id %} id="{{ id }}"{% endif %}
    {%- if class %} class="{{ class }}"{% endif %}
    {%- if required %} required aria-required="true"{% endif %}
    {%- if hasInstructions %} aria-describedby="{{ field.getNamespace() }}-{{ id }}-instructions"{% endif %}
    {%- if value %} value="{{ value }}"{% endif %}
    {%- if min is not null %} min="{{ min }}"{% endif %}
    {%- if max is not null %} max="{{ max }}"{% endif %}
    {%- if step is not null %} step="0.{{ step }}"{% endif %}
    {{- dataAttributes|raw -}}
>
```

The `min` variable is set toward the top based on the `field.min` value available to the template:

``` twig
{%- set min = field.min ? field.min : null %}
```

And later referenced just as `min` when outputting the value in the template:

``` twig
{%- if min is not null %} min="{{ min }}"{% endif %}
```
If that's not behaving the same way for you, please post a full example of the template you are using or, if we need to hop on a short hangout to troubleshoot, hit me up as BenParizek on Craft Discord or drop me a note at sprout@barrelstrengthdesign.com with a few times that work for you.

**Comment by janmeeus** [comment]
@BenParizek 

I tested with both the Basic Templates Number Field aswell as my custom (which are identical) and both times the `min="0"` did not show in the front-end. Only if I choose a min that is higher (so 1 and above) it shows in the front-end.

So I changed:

`{%- set min = field.min ? field.min : null %}
`
to
`{%- set min = field.min ? field.min : 0 %}
`

and that did the trick **for my particular issue**.

**Comment by BenParizek** [comment]
@janmeeus I believe I was mixed up here and that I fixed the issue you were experiencing in the Accessible Templates but had not corrected it in the Basic templates. 

While you may have solved this for now, just to note, I've made the fix in both base templates in the most recent release v3.8.8.
